parameters:
    db:
        username: 2
        password: 3
    oauth_clients:
        weixin:
            name: 微信网页登录接口
            class:  App\OAuth\Client\WeixinWebOAuthClient
            key:    wx3177719cde4ebeca
            secret: 0a056a510c813febba41113533338b3e
            apply_url:  https://open.weixin.qq.com/cgi-bin/frame?t=home/web_tmpl&lang=zh_CN
    biz_config:
        debug: "%kernel.debug%"
        db.options: "%biz_db_options%"
        root_directory: "%kernel.root_dir%/../"
        cache_directory: "%kernel.cache_dir%"
        log_directory: "%kernel.logs_dir%"
        kernel.root_dir: "%kernel.root_dir%"
        theme.directory: "%kernel.root_dir%/../web/themes"
    biz_db_options:
         url: '%env(resolve:DATABASE_URL)%'
         driver: pdo_mysql
         charset: utf8mb4
         server_version: '5.7'
         default_table_options:
             charset: utf8mb4
             collate: utf8mb4_unicode_ci